#!/bin/bash
#SBATCH --mem=2G
#SBATCH --account=halla
#SBATCH --mail-user=ktevans@jlab.org
#SBATCH --mail-type=END
#SBATCH --time=30:00:00

build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm0.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm1.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm2.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm3.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm4.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm5.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm6.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm7.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm8.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm9.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm10.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm11.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm12.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm13.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm14.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm15.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm16.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm17.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm18.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryAnalysis100mm19.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm0.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm1.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm2.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm3.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm4.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm5.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm6.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm7.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm8.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm9.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm10.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm11.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm12.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm13.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm14.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm15.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm16.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm17.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm18.C()'
build/reroot -l -b -q 'scripts/PrimAnalysis/NS_PrimaryUDAnalysis100mm19.C()'
